# 作業目標:

    通過建立多層的神經網路, 了解權值矩陣更新

# 作業重點: 

3  層神經網路

通過增加更多的中間層，以對更多關係的組合進行建模

syn1 權值矩陣將隱層的組合輸出映射到最終結果，

而在更新 syn1 的同時，還需要更新 syn0 權值矩陣，

以從輸入資料中更好地產生這些組合

In [4]:
import numpy as np
 
# Sigmoid 函數可以將任何值都映射到一個位於 0 到  1 範圍內的值。通過它，我們可以將實數轉化為概率值
def nonlin(x,deriv=False):
    if(deriv==True):
        return x*(1-x)
    return 1/(1+np.exp(-x))

X = np.array([  [0,0,1],
                [0,1,1],
                [1,0,1],
                [1,1,1] ])  
        
# define y for output dataset     
y = np.array([[0,0,1,1]]).T


In [18]:

# seed random numbers to make calculation
# deterministic (just a good practice)
np.random.seed(1)
#亂數設定產生種子得到的權重初始化集仍是隨機分佈的，
#但每次開始訓練時，得到的權重初始集分佈都是完全一致的。
 
# initialize weights randomly with mean 0
syn0 = 2*np.random.random((3,3)) - 1
# define syn1
iter = 0
#該神經網路權重矩陣的初始化操作。
#用 “syn0” 來代指 (即“輸入層-第一層隱層”間權重矩陣）
#用 “syn1” 來代指 (即“輸入層-第二層隱層”間權重矩陣）
syn1 = 2*np.random.random((3,1)) - 1
print(syn1)

[[ 0.07763347]
 [-0.16161097]
 [ 0.370439  ]]


In [21]:
l0 = X
print(l0)
print("\n")
print(syn0)
print("\n")
l1 = nonlin(np.dot(l0,syn0))  
print(l1)
l2 = np.dot(l1,syn1)
print(l2)

[[0 0 1]
 [0 1 1]
 [1 0 1]
 [1 1 1]]


[[-0.16595599  0.44064899 -0.99977125]
 [-0.39533485 -0.70648822 -0.81532281]
 [-0.62747958 -0.30887855 -0.20646505]]


[[0.34808226 0.4233885  0.44856632]
 [0.26447955 0.26593088 0.26467929]
 [0.31143146 0.53289503 0.23036767]
 [0.23347892 0.36014894 0.11695787]]
[[0.12476506]
 [0.07560265]
 [0.02339299]
 [0.00324752]]


神經網路訓練
for 迴圈反覆運算式地多次執行訓練代碼，使得我們的網路能更好地擬合訓練集

In [11]:
for iter in range(10000):
    # forward propagation
    l0 = X
    l1 = nonlin(np.dot(l0,syn0))    

    '''
    新增
    l2_error 該值說明了神經網路預測時“丟失”的數目。
    l2_delta 該值為經確信度加權後的神經網路的誤差，除了確信誤差很小時，它近似等於預測誤差。
    '''
 
    # how much did we miss?
    l1_error = y - l1
 
    # multiply how much we missed by the 
    # slope of the sigmoid at the values in l1
    l1_delta = l1_error * nonlin(l1,True)
    
    # update weights
    syn0 += np.dot(l0.T,l1_delta)
    
    l2 = nonlin(np.dot(l1,syn1))
    
    # how much did we miss?
    l2_error = y - l2

    # multiply how much we missed by the 
    # slope of the sigmoid at the values in l1
    l2_delta = l2_error * nonlin(l2,True)    

    # syn1 update weights
    syn1 += np.dot(l1.T,l2_delta)
    
print("Output l1 After Training:")
print(l1)
print("Output l2 After Training:")
print(l2)

ValueError: shapes (4,1) and (3,1) not aligned: 1 (dim 1) != 3 (dim 0)